project_name: hockey-stick

version: 2

before:
  hooks:
    - go mod tidy

builds:
    - id: hockey-stick
      binary: hockey-stick
      main: .
      env:
        - CGO_ENABLED=0
      goos:
        - linux
      goarch:
        - amd64 # x86_64
        - arm64 # aarch64

archives:
  - id: targz
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else}}{{ .Arch }}{{ end }}

nfpms:
  - id: debrpm
    package_name: hockey-stick
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else}}{{ .Arch }}{{ end }}
    vendor: udontur
    homepage: https://github.com/udontur/hockey-stick
    maintainer: Hadrian <contact@hadrian.cc>
    description: A terminal tool that finds your ideal hockey stick specs.
    license: MIT
    formats:
        - deb
        - rpm
    bindir: /usr/bin
