# vhs demo.tape

Output demo.gif

Require echo

Set Shell "bash"
Set FontSize 32
Set Width 1200
Set Height 800

Type "hockey-stick" Sleep 250ms Enter Sleep 500ms
Down Sleep 250ms Down Sleep 150ms Up Sleep 150ms Up Sleep 250ms
Enter Sleep 750ms
Down Sleep 250ms Down Sleep 1s
Enter Sleep 750ms
Type "54" Sleep 750ms Enter Sleep 250ms
Type "163" Sleep 750ms Enter Sleep 250ms
Down Sleep 1s
Enter Sleep 750ms
Down Sleep 150ms Down Sleep 150ms Down Sleep 150ms Down Sleep 150ms Down Sleep 150ms
Up Sleep 150ms Up Sleep 150ms
Sleep 2s Type "q" Sleep 500ms
